-- Manual Migration Script
-- Generated by AI Assistant per user request for manual execution

-- 1. Create uc_role table
CREATE TABLE IF NOT EXISTS `uc_role` (
    `id` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    `code` varchar(50) NOT NULL,
    `description` text,
    `status` varchar(50) NOT NULL DEFAULT 'enabled',
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uc_role_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 2. Ensure updated_at is nullable for existing tables (if not already applied)
-- Uncomment these lines if you encounter 'Field updated_at doesn\'t have a default value' errors
-- ALTER TABLE `uc_user` MODIFY COLUMN `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP;
-- ALTER TABLE `uc_menu` MODIFY COLUMN `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP;
-- ALTER TABLE `uc_application` MODIFY COLUMN `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP;
-- ALTER TABLE `oidc_client` MODIFY COLUMN `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP;
-- ALTER TABLE `oidc_payload` MODIFY COLUMN `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP;
