import { z } from "zod";

// A field in a dialog section: either a plain key string (read-only)
// or an object allowing editable / type / options overrides.
const ViewDialogFieldItemSchema = z.union([
  z.string(),
  z.object({
    key: z.string(),
    label: z.string().optional(),
    editable: z.boolean().optional(),
    // Override the field type for editing (e.g. force a text field to render as select)
    type: z.enum(["text", "textarea", "json", "select", "radio", "video"]).optional(),
    // Static options for select type. If omitted and type=select,
    // options are auto-generated by splitting the row value on commas.
    options: z.array(z.object({ label: z.string(), value: z.string() })).optional(),
    // Number of visible text rows for textarea fields
    rows: z.number().optional(),
    placeholder: z.string().optional(),
    validation: z.object({ required: z.boolean().optional() }).optional(),
  }),
]);

export const ViewDialogSectionSchema = z.object({
  title: z.string().optional(),
  columns: z.number().optional().default(2),
  fields: z.array(ViewDialogFieldItemSchema),
});

export const ActionDialogButtonSchema = z.object({
  label: z.string(),
  api: z.string(),
  method: z.enum(["GET", "POST", "PUT"]).optional().default("POST"),
  // Fields from row data to include in request body; omit to send all fields
  bodyFields: z.array(z.string()).optional(),
  // Static extra params merged into the request body
  params: z.record(z.string(), z.unknown()).optional(),
  // Close the dialog automatically on success
  closeOnSuccess: z.boolean().optional(),
});

export const ActionDialogConfigSchema = z.object({
  title: z.string().optional(),
  width: z.string().optional(),
  // When set, renders a custom registered component instead of the default DynamicDialog.
  // The component is looked up from the custom dialog registry by this name.
  component: z.string().optional(),
  sections: z.array(ViewDialogSectionSchema).optional().default([]),
  buttons: z.array(ActionDialogButtonSchema).optional(),
});

export type ActionDialogFieldItem = z.infer<typeof ViewDialogFieldItemSchema>;
export type ActionDialogConfig = z.infer<typeof ActionDialogConfigSchema>;
export type ViewDialogSection = z.infer<typeof ViewDialogSectionSchema>;
export type ActionDialogButton = z.infer<typeof ActionDialogButtonSchema>;
